### ISSUE TITLE
 raise err OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by TigerShuai** [intel/intel-extension-for-pytorch#394] opened 2023-07-29 13:48 UTC
### Describe the issue

环境为：Windows 11 企业版
显卡：因特尔 A770m 显卡

本地编译安装成功了intel-extension-for-pytorch、pytorch
![image](https://github.com/intel/intel-extension-for-pytorch/assets/35909241/3e8ca617-8acc-454b-bb4f-e9dc69948938)

运行提示：
 raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\ws\PycharmProjects\PyTorch_teach\intel-extension-for-pytorch\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.

😢😢😢wls2 和虚拟环境陆陆续续折腾好久了，现在windows也折腾不下去了.......

![image](https://github.com/intel/intel-extension-for-pytorch/assets/35909241/d73d2575-d1a6-4848-8ff0-8d63801507c8)

**Comment by ZhaoqiongZ** [comment] 2023-08-01 04:24
Hi @TigerShuai ，thanks for your try!  IPEX-XPU support WSL2 on windows system with Arc770 .
I write a detailed guide for you to follow to install ipex-xpu correctly in your wsl2 environment, If meet any issue, you can post it here and we will try to help you out.
Please follow my instruction to set the environment.
1. Install driver in Windows system with link https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html
2. verify the installation in Device Manager and with Intel Arc770 Graphics 
![image](https://github.com/intel/intel-extension-for-pytorch/assets/106125927/6e6165e5-55bf-41d0-b41f-1be643899527)
3. install wsl2 and install ubuntu 22.04 with wsl2
4. In ubuntu 22.04 system, follow the https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html#step-4-install-run-time-packages step4 and step5 to install driver , no need to install i386 packages
5. verify the installation by command clinfo -l , it will list the  Intel(R) Graphics [0x56a0]
![image](https://github.com/intel/intel-extension-for-pytorch/assets/106125927/7a883ba3-4109-4062-93a4-579dcb76c229)
6. create a conda virtual env to install the compiled torch/torchvison/ipex wheels or install from https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html#install-via-wheel-files, the latest ipex-xpu wheel 2.0 will be released in the end of this week.
7. install the oneAPI pkg from https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=offline&version=2023.2.0  with command `wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh` and install by `sudo sh ./l_BaseKit_p_2023.2.0.49397_offline.sh`
8. use the command below to activate oneapi env with the conda env you install the torch and ipex `export ONEAPI_HOME=intel/oneapi
source $ONEAPI_HOME/mkl/latest/env/vars.sh
source $ONEAPI_HOME/compiler/latest/env/vars.sh
source $ONEAPI_HOME/tbb/latest/env/vars.sh

export MKL_DPCPP_ROOT=$ONEAPI_HOME/mkl/latest
export INTEL_MKL_DIR=$ONEAPI_HOME/mkl/latest
export LD_LIBRARY_PATH=${MKL_DPCPP_ROOT}/lib:${MKL_DPCPP_ROOT}/lib/intel64:${LD_LIBRARY_PATH}
export LIBRARY_PATH=${MKL_DPCPP_ROOT}/lib:${MKL_DPCPP_ROOT}/lib/intel64:${LIBRARY_PATH}

python -c "import torch; import intel_extension_for_pytorch; print(torch.xpu.device_count()); print(torch.xpu.get_device_properties(0));"`
9. if you see the output contains `1
_DeviceProperties(name='Intel(R) Graphics [0x56a0]', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13004MB, max_compute_units=512, gpu_eu_count=512)`, it means the installation is correct and everything works fine, then you can begin your workload in this virtual environment.

**Comment by TigerShuai** [comment] 2023-08-01 04:33
> 你好@TigerShuai，感谢您的尝试！IPEX-XPU在Arc770的Windows系统上支持WSL2。 我写了一份详细的指南，供您按照在wsl2环境中正确安装ipex-xpu，如果遇到任何问题，您可以将其发布在这里，我们将尽力帮助您。 请按照我的指示设置环境。
> 
> 1. 在Windows系统中安装驱动程序，链接为https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html
> 2. 在设备管理器中验证安装并使用Intel Arc770显卡
>    ![图像](https://user-images.githubusercontent.com/106125927/257402995-6e6165e5-55bf-41d0-b41f-1be643899527.png)
> 3. 安装 wsl2 并使用 wsl2 安装 ubuntu 22.04
> 4. 在ubuntu 22.04系统中，按照https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html#step-4-install-run-time-packages步骤4和步骤5安装驱动程序、消耗安装i386
> 5. 通过命令 clinfo -l 验证安装，将会推出 Intel(R) 显卡 [0x56a0]
>    ![图像](https://user-images.githubusercontent.com/106125927/257403986-7a883ba3-4109-4062-93a4-579dcb76c229.png)
> 6. 创建一个 conda 虚拟环境来安装已编译的 torch/torchvison/ipex 轮子或从[https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html#install-via-安装Wheel-files](https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/installation.html#install-via-wheel-files)，最新的ipex-xpu Wheel 2.0将于本周末发布。
> 7. 使用命令从https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=offline&version=2023.2.0安装oneAPI pkg`wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh`并安装过程`sudo sh ./l_BaseKit_p_2023.2.0.49397_offline.sh`
> 8. 使用下面的命令使用安装 torch 和 ipex 的 conda env 激活 oneapi env `export ONEAPI_HOME=intel/oneapi 
>    source $ONEAPI_HOME/mkl/latest/env/vars.sh 
>    source $ONEAPI_HOME/compiler/latest/env/vars。 shsource 
>    $ ONEAPI_HOME/tbb/latest/env/vars.sh
> 
> 导出 MKL_DPCPP_ROOT=$ONEAPI_HOME/mkl/latest 导出 INTEL_MKL_DIR=$ONEAPI_HOME/mkl/latest 导出 LD_LIBRARY_PATH=${MKL_DPCPP_ROOT}/lib:${MKL_DPCPP_ROOT}/lib/intel64:${LD_LIBRARY_PATH} 导出 LIBRARY_PATH=${MKL_DPCPP_ROOT} /库:${MKL_DPCPP_ROOT}/lib/intel64:${LIBRARY_PATH}
> 
> python -c“导入火炬；导入intel_extension_for_pytorch；打印（torch.xpu.device_count（））；打印（torch.xpu.get_device_properties（0））；” `9. if you see the output contains`1 _DeviceProperties(name='英特尔(R) 显卡 [0x56a0]'、 platform_name='Intel(R) 0level'、dev_type='gpu、support_fp64=0、total_memory=13004MB、max_compute_units=512、gpu_eu_count=512)` ，这意味着安装正确并且一切正常，然后您可以在该虚拟环境中中开始您的工作负载。

感谢您，wsl2的方式，我看到官方文档的详细介绍了，没有疑问了，请问目前如果我不通过wsl2,只通过Windows 去安装环境做模型训练，可行吗？
目前我是本地编译完了，运行测试py文件时，就会提示：raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\ws\PycharmProjects\PyTorch_teach\intel-extension-for-pytorch\intel_extension_for_pytorch\bin\intel-ext-pt- gpu.dll”或依赖项之一。

**Comment by ZhaoqiongZ** [comment] 2023-08-01 04:36
Hi @TigerShuai , ipex is not official support original windows OS, so we have to use WSL2 to train the model on xpu.

**Comment by TigerShuai** [comment] 2023-08-01 04:38
> 你好@TigerShuai，ipex官方不支持原版windows操作系统，所以我们必须使用WSL2在xpu上训练模型。

好的好的，了解了。我换wsl2,感谢您🤝🤝🤝

**Comment by ZhaoqiongZ** [comment] 2023-08-04 01:47
Hi @TigerShuai , we are now start experimental support for original windows system along with the new release for v2.0.110 ， please follow the installation link here https://intel.github.io/intel-extension-for-pytorch/xpu/2.0.110+xpu/tutorials/installations/windows.html .

**Comment by TigerShuai** [comment] 2023-08-10 06:17
> 

您好，大佬，按照您的建议，我现在已经可以跑起来了，新的文档里面应该是把启动 call "C:\Intel\oneAPI\setvars.bat" 给忘记了
目前最新的问题，我运行在核显上跑Complete - Float32 Example 是通过的，但是通过查询API文档， 
设置：
torch.xpu.set_device(torch.device('xpu:1')) # 设置选择当前外置gpu
device = torch.device('xpu:1')
将启动gpu设置为额外的A770的独显就无法跑通 demo了
错误日志为：
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Native API failed. Native API returns: -997 (Command failed to enqueue/execute) -997 (Command failed to enqueue/execute)

**Comment by jingxu10** [comment] 2023-08-10 07:32
不一定要激活oneAPI的所有内容·call "C:\Intel\oneAPI\setvars.bat"·，光激活dpcpp compiler和mkl的环境就好了。
```
call {DPCPPROOT}\env\vars.bat
call {MKLROOT}\env\vars.bat
```

你跑的是examples里的例子吗？
能跑一下https://github.com/intel/intel-extension-for-pytorch/blob/master/scripts/collect_env.py，然后把输出发上来看看嘛？

**Comment by TigerShuai** [comment] 2023-08-10 07:35
> 不一定要激活oneAPI的所有内容`call "C:\Intel\oneAPI\setvars.bat"`，光激活dpcpp compiler和mkl的环境就好了。
> 
> ```
> call {DPCPPROOT}\env\vars.bat
> call {MKLROOT}\env\vars.bat
> ```
> 
> 你跑的是examples里的例子吗？ 能跑一下`https://github.com/intel/intel-extension-for-pytorch/blob/master/scripts/collect_env.py`，然后把输出发上来看看嘛？

日志如下：

--------------------------------------------------------------------
'hipconfig' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Warning: hipconfig --rocmpath failed, assuming /opt/rocm
Collecting environment information...
PyTorch version: 2.0.0a0+gitc6a572f
PyTorch CXX11 ABI: No
IPEX version: 2.0.110+gitba7f6c1
IPEX commit: ba7f6c127
Build type: Release

OS: Microsoft Windows 11 企业版
GCC version: (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 13.1.0
Clang version: 16.0.5
IGC version: 2023.2.0 (2023.2.0.20230627)
CMake version: version 3.27.1
Libc version: N/A

Python version: 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Iris(R) Xe Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=26043MB, max_compute_units=96, gpu_eu_count=96)
[1] _DeviceProperties(name='Intel(R) Arc(TM) A770M Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13004MB, max_compute_units=512, gpu_eu_count=512)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+gitba7f6c1
[pip3] numpy==1.25.2
[pip3] torch==2.0.0a0+gitc6a572f
[pip3] torchvision==0.15.1
[conda] intel-extension-for-pytorch 2.0.110+gitba7f6c1          pypi_0    pypi
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitc6a572f          pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

**Comment by TigerShuai** [comment] 2023-08-10 10:23
> > 不一定要激活oneAPI的所有内容`call "C:\Intel\oneAPI\setvars.bat"`，光激活dpcpp compiler和mkl的环境就好了。
> > ```
> > call {DPCPPROOT}\env\vars.bat
> > call {MKLROOT}\env\vars.bat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你跑的是examples里的例子吗？ 能跑一下`https://github.com/intel/intel-extension-for-pytorch/blob/master/scripts/collect_env.py`，然后把输出发上来看看嘛？
> 
> 日志如下：
> 
> 'hipconfig' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 Warning: hipconfig --rocmpath failed, assuming /opt/rocm Collecting environment information... PyTorch version: 2.0.0a0+gitc6a572f PyTorch CXX11 ABI: No IPEX version: 2.0.110+gitba7f6c1 IPEX commit: [ba7f6c1](https://github.com/intel/intel-extension-for-pytorch/commit/ba7f6c127d8157e698c85611bd5692db9f449a05) Build type: Release
> 
> OS: Microsoft Windows 11 企业版 GCC version: (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 13.1.0 Clang version: 16.0.5 IGC version: 2023.2.0 (2023.2.0.20230627) CMake version: version 3.27.1 Libc version: N/A
> 
> Python version: 3.9.17 (main, Jul 5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] (64-bit runtime) Python platform: Windows-10-10.0.22621-SP0 Is XPU available: True DPCPP runtime version: N/A MKL version: N/A GPU models and configuration: [0] _DeviceProperties(name='Intel(R) Iris(R) Xe Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=26043MB, max_compute_units=96, gpu_eu_count=96) [1] _DeviceProperties(name='Intel(R) Arc(TM) A770M Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=0, total_memory=13004MB, max_compute_units=512, gpu_eu_count=512) Intel OpenCL ICD version: N/A Level Zero version: N/A
> 
> CPU: Architecture=9 CurrentClockSpeed=2300 DeviceID=CPU0 Family=198 L2CacheSize=11776 L2CacheSpeed= Manufacturer=GenuineIntel MaxClockSpeed=2300 Name=12th Gen Intel(R) Core(TM) i7-12700H ProcessorType=3 Revision=
> 
> Versions of relevant libraries: [pip3] intel-extension-for-pytorch==2.0.110+gitba7f6c1 [pip3] numpy==1.25.2 [pip3] torch==2.0.0a0+gitc6a572f [pip3] torchvision==0.15.1 [conda] intel-extension-for-pytorch 2.0.110+gitba7f6c1 pypi_0 pypi [conda] numpy 1.25.2 pypi_0 pypi [conda] torch 2.0.0a0+gitc6a572f pypi_0 pypi [conda] torchvision 0.15.1 pypi_0 pypi

我尝试了重启、开关因特尔显卡驱动，
call      C:\Intel\oneAPI\setvars.bat
call  "C:\Intel\oneAPI\mkl\latest\env\vars.bat"
call    "C:\Intel\oneAPI\dpcpp-ct\latest\env\vars.bat"
call    "C:\Intel\oneAPI\compiler\latest\env\vars.bat"

偶发性的可以跑通..... 不知道具体是什么原因导致的
大部分时候都是报错：
RuntimeError: Native API failed. Native API returns: -997 (Command failed to enqueue/execute) -997 (Command failed to enqueue/execute)


偶尔能跑通的时候会打印如下日志：
onednn_verbose,info,oneDNN v3.2.0 (commit 67bc621a2da4aefc51f0a59b2af2398fa1d3e1c8)
onednn_verbose,info,cpu,runtime:threadpool,nthr:10
onednn_verbose,info,cpu,isa:Intel AVX2 with Intel DL Boost
onednn_verbose,info,gpu,runtime:DPC++
onednn_verbose,error,ocl,errcode -54,CL_INVALID_WORK_GROUP_SIZE,src/gpu/ocl/ocl_gpu_kernel.cpp:224
onednn_verbose,info,gpu,engine,0,backend:Level Zero,name:Intel(R) Iris(R) Xe Graphics,driver_version:1.3.26370,binary_kernels:disabled
onednn_verbose,info,gpu,engine,1,backend:Level Zero,name:Intel(R) Arc(TM) A770M Graphics,driver_version:1.3.26370,binary_kernels:disabled
onednn_verbose,info,experimental features are enabled
onednn_verbose,info,use batch_normalization stats one pass is enabled
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,error,ocl,errcode -54,CL_INVALID_WORK_GROUP_SIZE,src/gpu/ocl/ocl_gpu_kernel.cpp:224


太难了，太难了.........😢😢😢😢😢😢

**Comment by jingxu10** [comment] 2023-08-10 21:03
GCC version: (x86_64-posix-seh-rev1, Built by MinGW-Builds project) 13.1.0
你是在MinGW里跑的吗？还是在一个干净的Windows Command Prompt里跑的？

**Comment by Nuullll** [comment] 2023-08-18 12:18
```
RuntimeError: Native API failed. Native API returns: -997 (Command failed to enqueue/execute) -997 (Command failed to enqueue/execute)
```
This happened to me when I have my IPEX docker running and launch SD Web UI from native windows command line at the same time. Quitting the docker engine (and probably a reboot) solved my issue.

**Comment by ZhaoqiongZ** [comment] 2024-05-08 04:56
Hi @TigerShuai , 请问你有尝试过 Windows Installation with latest IPEX 么?  
https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip

**Comment by ZhaoqiongZ** [comment] 2024-06-03 00:53
The issue is closed due to inactivity. Feel free to reopen it if your problem has not been resolved

**Closed by ZhaoqiongZ** 2024-06-03 00:53 UTC
Labels: ARC, UserExperience
