### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by JudeDavis1** [intel/intel-extension-for-pytorch#218] opened 2022-03-19 22:15 UTC
Why is this error occurring when running setup.py?

subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

**Comment by JudeDavis1** [comment] 2022-03-20 08:36
After those changes I made, there was an error in version.cpp. It said that there was no closing ". 

The code was formatted like this:

foo = "--
HEAD";

Any way to fix this?

**Comment by JudeDavis1** [comment] 2022-03-20 08:39
I could install it using pip because AVX something wasn't supported. Is there a way I can counter this since I have slightly older intel hardware?

**Comment by JudeDavis1** [comment] 2022-03-20 09:13
Does it support AVX1?

**Comment by EikanWang** [comment] 2022-03-21 01:29
> Does it support AVX1?

Yes, the extension will auto dispatch to SSE if the machine does not support AVX2.

**Comment by EikanWang** [comment] 2022-03-21 01:30
> I couldn't install it using pip because AVX something wasn't supported. Is there a way I can counter this since I have slightly older intel hardware?

Do you mean you could install ipex? Could you share your error log here?

**Comment by EikanWang** [comment] 2022-03-21 01:36
May I know you git version? 

> After those changes I made, there was an error in version.cpp. It said that there was no closing ".
> 
> The code was formatted like this:
> 
> foo = "-- HEAD";
> 
> Any way to fix this?

May I know your git version? I could run "git rev-parse HEAD" normally. Seems like I should revert this PR.
![image](https://user-images.githubusercontent.com/55483091/159195439-878e96de-c0cd-49eb-968f-aa930743a896.png)

**Comment by JudeDavis1** [comment] 2022-03-21 07:43
> > I couldn't install it using pip because AVX something wasn't supported. Is there a way I can counter this since I have slightly older intel hardware?
> 
> 
> 
> Do you mean you could install ipex? Could you share your error log here?

Sorry I worded that weirdly. I could install the extension using pip, but couldn't import it. 

>>> import intel_extension_for_pytorch
AVX2 not supported
EXIT

**Comment by JudeDavis1** [comment] 2022-03-21 07:46
> May I know you git version? 
> 
> 
> 
> > After those changes I made, there was an error in version.cpp. It said that there was no closing ".
> 
> > 
> 
> > The code was formatted like this:
> 
> > 
> 
> > foo = "-- HEAD";
> 
> > 
> 
> > Any way to fix this?
> 
> 
> 
> May I know your git version? I could run "git rev-parse HEAD" normally. Seems like I should revert this PR.
> 
> ![image](https://user-images.githubusercontent.com/55483091/159195439-878e96de-c0cd-49eb-968f-aa930743a896.png)
> 
> 

Latest git version. I could run in from the command line too, but I'm still getting that error.

**Comment by JudeDavis1** [comment] 2022-03-21 20:23
Okay now the build is working. But after i built it from source, I still get this error when importing ipex: 
The extension binary is AVX2 while current machine does not support AVX2.

**Comment by EikanWang** [comment] 2022-03-23 02:36
IPEX also supports non-avx platform. Did you mean ipex would raise an error to prompt you the extension is avx2-only binary?

**Comment by JudeDavis1** [comment] 2022-03-23 07:12
Precisely - yes.

**Comment by JudeDavis1** [comment] 2022-03-23 07:12
Is this possibly a big or something?

**Comment by JudeDavis1** [comment] 2022-03-23 07:12
Bug*

**Comment by EikanWang** [comment] 2022-03-23 07:36
Could you try installing IPEX via PIP and try again? Soft reminder: you need to upgrade local PyTorch to 1.11.

```bash
conda install pytorch torchvision torchaudio cpuonly -c pytorch
pip install intel_extension_for_pytorch
```

**Comment by JudeDavis1** [comment] 2022-03-23 08:55
Thanks, I'll try that.

**Comment by JudeDavis1** [comment] 2022-03-23 18:43
Hi. I'm still getting this error:

The extension binary is AVX2 while current machine does not support AVX2.

PyTorch is running at v11 and everything's up to date. (This is using pip BTW)

**Comment by EikanWang** [comment] 2022-03-23 22:28
Got it. Thanks. we will reproduce it and fix it. @xuhancn , please help investigate it.

**Comment by xuhancn** [comment] 2022-03-24 01:25
> Got it. Thanks. we will reproduce it and fix it. @xuhancn , please help investigate it.

Need @zhuhaozhe evaluate how many non-avx implemention， we need finished all level kernel implemention.

**Comment by xuhancn** [comment] 2022-03-24 08:32
> Hi. I'm still getting this error when i try to import ipex:
> 
> The extension binary is AVX2 while current machine does not support AVX2.
> 
> PyTorch is running at v11 and everything's up to date. (This is using pip BTW)

@JudeDavis1 could you please run " cat /proc/cpuinfo" and copy output for me. I need this information to debug.

**Comment by JudeDavis1** [comment] 2022-03-24 17:02
> > Hi. I'm still getting this error when i try to import ipex:
> > The extension binary is AVX2 while current machine does not support AVX2.
> > PyTorch is running at v11 and everything's up to date. (This is using pip BTW)
> 
> @JudeDavis1 could you please run " cat /proc/cpuinfo" and copy output for me. I need this information to debug.

Here it is:

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      :        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0xffffffff
cpu MHz         : 2501.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave osxsave avx lahf_lm ibrs ibpb stibp ssbd
bogomips        : 5002.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      :        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0xffffffff
cpu MHz         : 2501.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave osxsave avx lahf_lm ibrs ibpb stibp ssbd
bogomips        : 5002.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      :        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0xffffffff
cpu MHz         : 2501.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave osxsave avx lahf_lm ibrs ibpb stibp ssbd
bogomips        : 5002.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      :        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0xffffffff
cpu MHz         : 2501.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave osxsave avx lahf_lm ibrs ibpb stibp ssbd
bogomips        : 5002.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual

**Comment by xuhancn** [comment] 2022-03-24 19:17
@JudeDavis1 

Sorry for inconvenience, our extension minimal required CPU ISA support AVX2. Your CPU is not meet the requirement.
We will add more CPU compatiable check in further version.

**Comment by JudeDavis1** [comment] 2022-03-24 19:18
But @EikanWang said that it can detect a different version and use that?

**Comment by JudeDavis1** [comment] 2022-03-24 19:19
Can it not work with AVX1 or SSA?

**Comment by JudeDavis1** [comment] 2022-03-24 19:20
> IPEX also supports non-avx platform. Did you mean ipex would raise an error to prompt you the extension is avx2-only binary?

This ^

**Comment by JudeDavis1** [comment] 2022-03-24 19:20
> > Does it support AVX1?
> 
> 
> 
> Yes, the extension will auto dispatch to SSE if the machine does not support AVX2.
> 
>

**Comment by EikanWang** [comment] 2022-03-25 00:33
@JudeDavis1, I checked internally. The code contains the non-AVX path but we don't enable it now. Because it is hard to get better performance and some advanced kernels have not implemented the non-AVX version. Besides that, may I know the use case here? Do you want to try to use IPEX to accelerate some models on the client?

**Comment by JudeDavis1** [comment] 2022-03-25 15:54
> @JudeDavis1, I checked internally. The code contains the non-AVX path but we don't enable it now. Because it is hard to get better performance and some advanced kernels have not implemented the non-AVX version. Besides that, may I know the use case here? Do you want to try to use IPEX to accelerate some models on the client? 

Yep I'm just trying to speed up my model training on my current hardware as I can't yet afford any new hardware. I primarily use PyTorch but I've been looking everywhere and IPEX seemed to be a good fit, but it doesn't work on my hardware.

**Closed** 2022-06-29 02:22 UTC
Labels: bug
