### ISSUE TITLE
LSTM failed to run on cpu after running once on ipex

### ISSUE THREAD

**Issue by zhentaocc** [intel/intel-extension-for-pytorch#187] opened 2021-10-13 07:29 UTC
Running following script will raise an error. The problem is that in evaluation if we run on ipex, the weight in lstm will be reshaped into 5 dimension, and then in the following training with dropout > 0 it's forced back to run on cpu where 2d weights are expected.

Maybe in fallback_lstm copying lstm module back to cpu, there should be extra lines to fall back the weights to 2d to run on cpu.

A simple unit test:

```
import torch
import torch.nn as nn
import intel_pytorch_extension as ipex


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.lstm = nn.LSTM(2, 16, 1, batch_first=True, dropout=0.2)

    def forward(self, input):
        return self.lstm(input)


model = Model().to(ipex.DEVICE)
input = torch.ones(1, 16, 2)
with torch.no_grad():
    model.eval()
    o1 = model(input.to(ipex.DEVICE))
model.train()
o2 = model(input)
```
Error message:
```
/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/torch/nn/modules/rnn.py:63: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Traceback (most recent call last):
  File "/home/zhentaoc/PycharmProjects/chronos-benchmark/forecaster/models/test.py", line 21, in <module>
    o2 = model(input)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhentaoc/PycharmProjects/chronos-benchmark/forecaster/models/test.py", line 12, in forward
    return self.lstm(input)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 662, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/intel_pytorch_extension/ops/lstm.py", line 57, in lstm
    return ipex_lstm(*args, device=device)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/intel_pytorch_extension/ops/lstm.py", line 9, in ipex_lstm
    return fallback_lstm(input, hx, _flat_weights, bias, num_layers, dropout, training, bidirectional, batch_first, device=device)
  File "/home/zhentaoc/anaconda3/envs/bigdl/lib/python3.7/site-packages/intel_pytorch_extension/ops/lstm.py", line 38, in fallback_lstm
    output = VF_lstm(*args_cpu)
RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 5D
```

**Comment by zhentaocc** [comment] 2021-10-18 01:31
Please could you check the script I provided?  I'm trying to use ipex during evaluation by copying input to ipex.DEVICE while run on cpu during training with input on cpu. So I am sure this is what you mentioned "obtain the benefit for inference" and "fall back to the default PyTorch operator". So if this is an expected practice, there should be no error but now there is.

**Comment by EikanWang** [comment] 2021-11-26 06:42
@zhentaocc , we will release IPEX 1.10. Regarding IPEX 1.10, we switched the underhood device from XPU to CPU for the CPU devices. @chunyuan-w has verified the issue is fixed on IPEX 1.10. I wonder if you could try IPEX 1.10(https://github.com/intel/intel-extension-for-pytorch/tree/release/1.10) for this issue. I hope the coming IPEX 1.10 could help you to improve the model training.

**Comment by EikanWang** [comment] 2021-11-29 08:49
I will close this issue first. If you still encounter this issue on IPEX 1.10, please feel free to reopen it.

**Closed by EikanWang** 2021-11-29 08:49 UTC

**Comment by zhentaocc** [comment] 2021-11-29 09:16
> I will close this issue first. If you still encounter this issue on IPEX 1.10, please feel free to reopen it.

thx. Will check that.
