### ISSUE TITLE
can't use ComfyUI_examples's FLUX fp8 workflow in ipex=2.1.30 and 2.1.40

### ISSUE THREAD

**Issue by kingsdom-sk** [intel/intel-extension-for-pytorch#691] opened 2024-08-18 08:05 UTC
### Describe the issue

Hi, my PC info is i5-12600KF, 32GRAM, intel ARC A770 16G，windows 11， 22H2

I can use Comfyui's default workflow  with SD1.5, SDXL, and SDXLlighting.

But  I used https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version with FLUX fp8 models https://huggingface.co/Kijai/flux-fp8/tree/main,  failured.

I tried ipex=2.1.30 and 2.1.40, all failured. 

GET error  log below

C:\Users\Administrator>conda activate ipex-arc

(ipex-arc) C:\Users\Administrator>cd "C:\Program Files (x86)\Intel\oneAPI"

(ipex-arc) C:\Program Files (x86)\Intel\oneAPI>setvars.bat
:: initializing oneAPI environment...
   Initializing Visual Studio command-line environment...
   Visual Studio version 17.11.0 environment configured.
   "C:\Program Files\Microsoft Visual Studio\2022\Community\"
   Visual Studio command-line environment initialized for: 'x64'
:  compiler -- latest
:  debugger -- latest
:  dev-utilities -- latest
:  dpcpp-ct -- latest
:  dpl -- latest
:  mkl -- latest
:  ocloc -- latest
:  tbb -- latest
:: oneAPI environment initialized ::

(ipex-arc) C:\Program Files (x86)\Intel\oneAPI>cd ..

(ipex-arc) C:\Program Files (x86)\Intel>cd \

(ipex-arc) C:\>cd ComfyUI-240

(ipex-arc) C:\ComfyUI-240>python.exe main.py --use-split-cross-attention
C:\miniconda3\envs\ipex-arc\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\miniconda3\envs\ipex-arc\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Total VRAM 15931 MB, total RAM 32611 MB
pytorch version: 2.1.0.post3+cxx11.abi
Set vram state to: NORMAL_VRAM
Device: xpu
Using split optimization for cross attention
[Prompt Server] web root: C:\ComfyUI-240\web

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI-240\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
C:\miniconda3\envs\ipex-arc\lib\site-packages\intel_extension_for_pytorch\frontend.py:465: UserWarning: Conv BatchNorm folding failed during the optimize process.
  warnings.warn(
C:\miniconda3\envs\ipex-arc\lib\site-packages\intel_extension_for_pytorch\frontend.py:472: UserWarning: Linear BatchNorm folding failed during the optimize process.
  warnings.warn(
clip missing: ['text_projection.weight']
Requested to load Flux
Loading 1 new model
loaded partially 8749.598906250001 8739.421936035156 0
!!! Exception during processing !!! The model is mixed with different device type
Traceback (most recent call last):
  File "C:\ComfyUI-240\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-240\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-240\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-240\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI-240\comfy_extras\nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "C:\ComfyUI-240\comfy\samplers.py", line 706, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
  File "C:\ComfyUI-240\comfy\sampler_helpers.py", line 66, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
  File "C:\ComfyUI-240\comfy\model_management.py", line 527, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "C:\ComfyUI-240\comfy\model_management.py", line 328, in model_load
    self.real_model = ipex.optimize(self.real_model.eval(), graph_mode=True, concat_linear=True)
  File "C:\miniconda3\envs\ipex-arc\lib\site-packages\intel_extension_for_pytorch\frontend.py", line 353, in optimize
    raise RuntimeError("The model is mixed with different device type")
RuntimeError: The model is mixed with different device type

Prompt executed in 24.25 seconds

**I try  comand line with another option,  the programe abort , and get the error log below:**

**(ipex-arc) C:\ComfyUI-240>python.exe main.py**
C:\miniconda3\envs\ipex-arc\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\miniconda3\envs\ipex-arc\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Total VRAM 15931 MB, total RAM 32611 MB
pytorch version: 2.1.0.post3+cxx11.abi
Set vram state to: NORMAL_VRAM
Device: xpu
Using pytorch cross attention
[Prompt Server] web root: C:\ComfyUI-240\web

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI-240\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
C:\miniconda3\envs\ipex-arc\lib\site-packages\intel_extension_for_pytorch\frontend.py:465: UserWarning: Conv BatchNorm folding failed during the optimize process.
  warnings.warn(
C:\miniconda3\envs\ipex-arc\lib\site-packages\intel_extension_for_pytorch\frontend.py:472: UserWarning: Linear BatchNorm folding failed during the optimize process.
  warnings.warn(
clip missing: ['text_projection.weight']
Requested to load Flux
Loading 1 new model

**(ipex-arc) C:\ComfyUI-240>python.exe main.py --disable-ipex-optimize**
C:\miniconda3\envs\ipex-arc\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\miniconda3\envs\ipex-arc\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Total VRAM 15931 MB, total RAM 32611 MB
pytorch version: 2.1.0.post3+cxx11.abi
Set vram state to: NORMAL_VRAM
Device: xpu
Using pytorch cross attention
[Prompt Server] web root: C:\ComfyUI-240\web

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI-240\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
clip missing: ['text_projection.weight']
Requested to load Flux
Loading 1 new model

(ipex-arc) C:\ComfyUI-240>

**My system info:**

处理器	12th Gen Intel(R) Core(TM) i5-12600KF   3.70 GHz
机带 RAM	32.0 GB (31.8 GB 可用)
版本	Windows 11 专业版
版本	22H2
安装日期	‎2024/‎6/‎23
操作系统版本	22621.1702

(ipex-arc) C:\Users\Administrator>pip list
Package                     Version
--------------------------- ----------------------
aiohappyeyeballs            2.3.6
aiohttp                     3.10.3
aiosignal                   1.3.1
annotated-types             0.7.0
async-timeout               4.0.3
attrs                       24.2.0
certifi                     2024.7.4
cffi                        1.17.0
charset-normalizer          3.3.2
colorama                    0.4.6
einops                      0.8.0
filelock                    3.15.4
frozenlist                  1.4.1
fsspec                      2024.6.1
huggingface-hub             0.24.5
idna                        3.7
intel_extension_for_pytorch 2.1.40+xpu
Jinja2                      3.1.4
kornia                      0.7.3
kornia_rs                   0.1.5
MarkupSafe                  2.1.5
mpmath                      1.3.0
multidict                   6.0.5
networkx                    3.3
numpy                       1.26.4
packaging                   24.1
pillow                      10.4.0
pip                         24.2
psutil                      6.0.0
pycparser                   2.22
pydantic                    2.8.2
pydantic_core               2.20.1
PyYAML                      6.0.2
regex                       2024.7.24
requests                    2.32.3
safetensors                 0.4.4
scipy                       1.14.0
sentencepiece               0.2.0
setuptools                  72.1.0
soundfile                   0.12.1
spandrel                    0.3.4
sympy                       1.13.2
tokenizers                  0.13.3
torch                       2.1.0.post3+cxx11.abi
torchaudio                  2.1.0.post3+cxx11.abi
torchsde                    0.2.6
torchvision                 0.16.0.post3+cxx11.abi
tqdm                        4.66.5
trampoline                  0.1.2
transformers                4.31.0
typing_extensions           4.12.2
urllib3                     2.2.2
wheel                       0.43.0
yarl                        1.9.4

**Comment by simonlui** [comment] 2024-08-18 09:09
This is a dupe of #687. What version of ComfyUI are you using? Not sure what 240 is, the latest stable release is [v0.0.8](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.0.8) which is from last Tuesday. This works on a Linux machine so not sure what is wrong with Windows.

**Comment by kingsdom-sk** [comment] 2024-08-18 09:38
> This is a dupe of #687. What version of ComfyUI are you using? Not sure what 240 is, the latest stable release is [v0.0.8](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.0.8) which is from last Tuesday. This works on a Linux machine so not sure what is wrong with Windows.

240 it means use ipex 2.1.40, i just separate from 2.1.30. I will try v0.0.8 late.

**Comment by simonlui** [comment] 2024-08-19 09:08
Oh okay. It's looking more and more like a Windows issue but being able to use the latest git version also would work in this situation. I think there is another stable release incoming after v0.0.8 soon given a lot of features have made it into the project since a release was done like TAESD previews for Flux and etc.

**Comment by ZailiWang** [comment] 2024-08-21 07:09
@simonlui  Thanks a lot for your help. @kingsdom-sk would you try with the latest version per the above comment?

**Comment by simonlui** [comment] 2024-08-22 11:46
@kingsdom-sk See https://github.com/intel/intel-extension-for-pytorch/issues/687#issuecomment-2304463360 in the other thread. I believe that should solve your issue.

**Comment by kingsdom-sk** [comment] 2024-08-23 12:49
> @simonlui Thanks a lot for your help. @kingsdom-sk would you try with the latest version per the above comment?

Sorry for my later reply, because I lost in WuKong.  I will try tomorrow.

**Comment by kingsdom-sk** [comment] 2024-08-25 08:10
> @kingsdom-sk See [#687 (comment)](https://github.com/intel/intel-extension-for-pytorch/issues/687#issuecomment-2304463360) in the other thread. I believe that should solve your issue.

I update comfyui to latest,  problem disappeared.  not with --fp8_e4m3fn-unet option.

**Comment by ZailiWang** [comment] 2024-08-26 00:55
Thanks for the confirmation.

**Closed by ZailiWang** 2024-08-26 00:55 UTC
Labels: XPU/GPU, Windows
